apiVersion: cloudbuild.googleapis.com/v1
kind: BuildTrigger
metadata:
  name: bpm-server-trigger
spec:
  github:
    owner: RoyeeB
    name: bpm-server
    push:
      branch: ^main$
  filename: cloudbuild.yaml
  serviceAccount: 731043621084-compute@developer.gserviceaccount.com
  options:
    logging: CLOUD_LOGGING_ONLY
